### PR TITLE
Document stage: N labels

### PR DESCRIPTION
**Pull request by foolip**
These are described in https://github.com/whatwg/meta/issues/290.

### CODE REVIEW

**Comment by annevk** [comment]
This file is generated from `labels.json` so this doesn't work as-is.

**Comment by foolip** [comment]
@annevk I've updated `labels.json` and run the update script.

**Review by annevk — APPROVED** [review]
Assuming you've ran the script (and thus validated the JSON), this looks good.

**Comment by foolip** [comment]
I've created the labels for HTML using the command line `python3 labels.py --token REDACTED --repository whatwg/html`.

**Comment by foolip** [comment]
I've run the script again with `--all-whatwg-standards` so these labels are now everywhere.

**Pull request merged**
