### PR TITLE
Suggest using the type:untestable label for wpt

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
See also https://github.com/w3c/web-performance/pull/18

**Comment by annevk** [comment]
I think you also need to adjust the other wording then. That we basically require a test unless it cannot be automated for some reason. If it cannot be automated, a manual test would be good to proof the suggested change as well as an issue to ask for it to be automatized (which should have that label).

**Comment by foolip** [comment]
If we want to keep allowing to punt on testing for "burdensome" reasons, I could say that either type:untestable *or* type:missing-coverage should be added. WDYT?

**Comment by annevk** [comment]
Sure.

**Comment by foolip** [comment]
Done.

**Pull request merged**
